name: build

on: [push, pull_request]

jobs:
  type-checking:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Type checking with Pyright
        run: |
          uv run poe types

  pre-commit-hooks:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Check all pre-commit hooks
        run: |
          uv run poe pre-commit

  unit-tests:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: ./.github/actions/init

      - name: Run all unit tests
        run: |
          uv run poe unit-tests

  lint:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Lint Python with Ruff
        run: |
          uv run poe lint
