name: build

on:
  push:
    branches:
      - main
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  type-checking:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Type checking with Pyright
        run: |
          uv run poe types

  pre-commit-hooks:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Check all pre-commit hooks
        run: |
          uv run poe pre-commit

  unit-tests:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Run all unit tests
        run: |
          uv run poe unit-tests

  lint:
    runs-on:
      group: gha-oqc-tech

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/init

      - name: Lint Python with Ruff
        run: |
          uv run poe lint

  publish:
    runs-on:
      group: gha-oqc-tech

    # Only publish if this is a passing version-tag push to main OR a manual workflow_dispatch
    needs: [type-checking, pre-commit-hooks, unit-tests, lint]
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/init

      - name: Build package
        run: |
          uv build

      - name: Publish to internal PyPI
        run: |
          uv publish \
            --publish-url ${{ vars.INTERNAL_PYPI_URL }} \
            --username ${{ secrets.INTERNAL_PYPI_USERNAME }} \
            --password ${{ secrets.INTERNAL_PYPI_PASSWORD }}
